/**
 * Helper functions.
 * 
 * @author Denis Power
 * 
 */

const fs=require("fs");

function createFileNamed(fileName, data){



    try{

        fs.writeFileSync(fileName,data);

      return  Promise.resolve(`
        
        The ${fileName} file was created succefully.
        
        `);


    }catch(e){

        return Promise.reject(e);

    }



}

function removeImportsAndExport(fileName,fileStringfied){

    const importStatement=/import(:?\s*){.*}(:?\s*)from(:?\s*)(:? ".*"|'.*'|`.*`)(:?\s*);*/g;
    const exportStatement=/export/g;

     if(fileStringfied instanceof String){ 
         
         fileStringfied.replace(importStatement, "");
        fileStringfied.replace(exportStatement, "");
         
         
     }else{ 
         throw new Error(`
         
         Ensure that the ${fileName} contains both import and export statements.
         
         `)
      
      }
    
    



}

function createGlobalVars(vars, fileStringfied){


    if(vars instanceof Array && fileStringfied instanceof String){


        fileStringfied+=`
        
        
        `;

        vars.forEach((_var)=>{

          fileStringfied+=`window.[${_var.name}]=${_var.value};`

        })


    }

    return fileStringfied;


}

function createIIFE(fileStringfied, v){


    if(fileStringfied instanceof String && v instanceof String){

        return `

        (function(){
 
            /**
             * Generated by Builder.
            *  @author Denis Power
            *  Inter - The Javascript framework designed to build highly interactive front-end apps.
            *  version:${v}
             * 2021-2022  
             * 
             */

          ${fileStringfied}


        })();
        
        
        
        `

    }


}

exports.createFileNamed=createFileNamed;
exports.removeImportsAndExport=removeImportsAndExport;
exports.createGlobalVars=createGlobalVars;
exports.createIIFE=createIIFE;
